### ISSUE TITLE
votes

### ISSUE THREAD

**Issue by malithmcr** [xdesro/personalsit.es#142]
Hello,

Isn't it cool to have Up voting system for each site? Who has most votes stay in the top. 

Just an idea.

**Comment by andybelldesign** [comment]
I’ll add this to the idea pile. I’d have to work out some sorta backend for this!

**Comment by malithmcr** [comment]
> I’ll add this to the idea pile. I’d have to work out some sorta backend for this!

yeah that's true.

**Comment by xdesro** [comment]
It's been a few years, but I reckon I'll close this one — I like that each build surfaces new sites randomly. Also, voting can often turn into a popularity contest, which I don't love.
