### ISSUE TITLE
Known Portfolio Sites

### ISSUE THREAD

**Issue by Martin-Pitt** [xdesro/personalsit.es#19]
Hi, here's a list exported from my Chrome via my tabs extension manager (Spaces).

Turned it into a task list, we can check off any added.

I do try to always add any non-white-dude sites I find with more bias to try balance it, but alas, it may be still quite skewed.

- [ ] https://zachsaucier.com/
- [ ] https://durimel.io/nel
- [ ] https://www.tristanbagot.com/#landing
- [ ] https://ste.vg/
- [ ] http://tobiasahlin.com/blog/meaningful-motion-w-action-driven-animation/
- [ ] http://tobiasahlin.com/moving-letters/#
- [ ] http://tonsky.me/projects/
- [ ] https://hajimewatanabe.jp/portfolio/
- [ ] http://www.aaronsherrill.com/
- [ ] https://lynnandtonic.com/
- [ ] http://www.elenwinata.com/
- [ ] https://raymondyang.design/projects/
- [ ] http://www.robinselmer.de/
- [ ] https://timseverien.com/
- [ ] http://agathecocco.com/cgi-sys/suspendedpage.cgi
- [ ] http://untitledseven.co.uk/
- [ ] https://vangeltzo.com/index.html
- [ ] https://www.andrewmcwatters.com/
- [ ] https://sarahdrasnerdesign.com/
- [ ] http://brandongregorycreative.com/index.html
- [ ] https://kyusuf.com/
- [ ] http://zomigi.com/
- [ ] https://www.jordanstephens.com/
- [ ] https://asciidisco.com/
- [ ] http://broccolini.net/
- [ ] https://juliebonnemoy.com/
- [ ] https://www.estellatse.com/
- [ ] http://punchesbears.com/
- [ ] https://sindresorhus.com/
- [ ] https://gaffen.co.uk/
- [ ] https://philna.sh/
- [ ] http://xtian.design/
- [ ] https://thomasslade.com/
- [ ] https://bkardell.com/
- [ ] http://possibles.ca/en/
- [ ] http://biron.io/
- [ ] http://macr.ae/
- [ ] http://wensday.co/
- [ ] https://baku89.com/?lang=en
- [ ] https://frankchimero.com/
- [ ] https://0x0ade.github.io/
- [ ] https://engzell.me/
- [ ] http://jonnotie.com/
- [ ] http://grayghostvisuals.com/
- [ ] https://bost.ocks.org/mike/
- [ ] http://juliangarnier.com/
- [ ] http://www.derschmale.com/
- [ ] https://www.theterrytucker.com/
- [ ] https://www.derekknox.com/
- [ ] http://www.robinpayot.com/#about
- [ ] http://marionlivet.com/
- [ ] http://soufianelasri.com/
- [ ] http://annethai.com/
- [ ] http://www.romainbarbier.com/
- [ ] https://www.unit9.com/
- [ ] https://essenmitsosse.de/
- [ ] https://lmgonzalves.com/
- [ ] http://digitostudio.com/
- [ ] http://www.thedazzlingdman.com/
- [ ] https://jmperezperez.com/
- [ ] https://nunoarruda.com/
- [ ] http://twotwentytwo.se/
- [ ] http://www.andreadlabarile.it/
- [ ] http://www.madethought.com/
- [ ] https://openai.com/
- [ ] http://wensday.co/
- [ ] http://smus.com/
- [ ] https://boyter.org/
- [ ] https://baku89.com/?lang=en
- [ ] http://localhost:5120/
- [ ] http://imabhi.in/
- [ ] https://moeamaya.com/
- [ ] http://sean.cm/
- [ ] http://blairneal.com/
- [ ] http://www.jamiecoulter.co.uk/
- [ ] http://daryl.github.io/
- [ ] https://codepen.io/jcoulterdesign/
- [ ] https://www.matserra.design/
- [ ] http://www.aaronsherrill.com/
- [ ] https://www.mariodesigns.co.uk/
- [ ] https://isralduke.com/
- [ ] http://hireflemming.webflow.io/
- [ ] https://yuanchuan.name/
- [ ] https://shaunlebron.github.io/#!/projects
- [ ] http://yang-zhang.me/
- [ ] https://galaxy.fili.nl/
- [ ] http://mathis-biabiany.fr/
- [ ] https://madclem.github.io/
- [ ] https://pori.design/
- [ ] http://www.greengoldenly.com/
- [ ] http://weareafk.co.uk/
- [ ] http://www.connorbell.ca/
- [ ] http://codenjoy.tv/portfolio
- [ ] https://robinrendle.com/
- [ ] https://nicksherman.com/
- [ ] https://epok.tech/
- [ ] https://codepen.io/jakob-e/
- [ ] http://designgal.org/
- [ ] http://alexbuzin.me/#
- [ ] https://jina.me/
- [ ] https://www.kempsterrrr.xyz/

**Comment by hankchizljaw** [comment]
Lovely, as I said on Twitter, I was hoping people would submit their own initially. Folks might be a bit surprised if their site appears on a directory.

Heck of a list though!

**Comment by Martin-Pitt** [comment]
Their website already opts into being on a global directory (google, bing, etc), I don't think it's a stretch if it appears elsewhere as well.

There are robots crawling everywhere doing this in an automated fashion, so yeah, a few humans creating a curated list is surprising; But it is a nice surprise.


This is an awesome list of international speakers, which would be worth going through checking for personal sites to add: https://github.com/karlhorky/awesome-speakers


Additionally I just want to say, I don't think you can expect people to submit their own. We need to be the agents of change in uplifting people.

> "Diversity is being invited to the party, inclusivity is being glad you're there." - @doramilitar

**Comment by hankchizljaw** [comment]
Yeh I understand your point. The point of this site is for people to share their websites with the world. It's not a semi-automated directory. 

I should update the intro to reflect that.

Also, if you want a big directory of personal sites like you outline above, you should go ahead and create one. This only took half an hour to put together :)
