### ISSUE TITLE
The website is down?

### ISSUE THREAD

**Issue by hszhakka** [xdesro/personalsit.es#271]
<img width="569" alt="Screenshot 2020-01-16 at 1 10 26 AM" src="https://user-images.githubusercontent.com/59011975/72455108-21b53a00-37fd-11ea-88f0-76fb00f46d30.png">

**Comment by xdesro** [comment]
Up-and-running again. I should've tested before merging — looks like a stray apostrophe in the YAML broke the build. 

https://github.com/xdesro/personalsit.es/commit/c36ef3690289bce93178337efab3c808ea4e6cdf#diff-e43c23e41182f0936e10fadbe0ecd528L2

We're still working on transferring the project between domain registrars and Netlify instances, so there'll be some bumps in the road.
