### ISSUE TITLE
Updating website screenshot

### ISSUE THREAD

**Issue by linusg** [xdesro/personalsit.es#446]
I made some visual changes to my website recently and noticed that the [screenshot](https://res.cloudinary.com/personalsites/image/upload/w_600/linus.dev.png) is not updated. Upon investigation and looking at the build script, it seems like it won't automatically do that, short of deleting the screenshot from cloudinary to get it regenerated - is that correct?

**Comment by xdesro** [comment]
Hey @linusg — that's correct. Unfortunately it'd just be too resource expensive to regenerate every screenshot on every build. I've gone ahead and recaptured the screenshot!
