### ISSUE TITLE
Dodgy website thumbnail capture

### ISSUE THREAD

**Issue by sarajw** [xdesro/personalsit.es#788]
For Sara Joy - https://sarajoy.dev

Thank you!

![Screenshot_20240206-213914~2](https://github.com/xdesro/personalsit.es/assets/88535714/cb6aeb8a-c116-42a6-b52b-03fe3ebec338)

**Comment by xdesro** [comment]
Updated! Sorry for the jank and thank you for openin' an issue :)

**Comment by sarajw** [comment]
Thank you so much!
